name: Pre-release

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: write

jobs:
  build-prerelease:
    name: Build pre-release
    uses: ./.github/workflows/release-pipeline.yml
    with:
      prerelease: true
    secrets: inherit
